services:
  - type: web
    name: balance-booking
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_SHOP
        value: d94663-4.myshopify.com
      - key: SHOPIFY_CLIENT_ID
        sync: false
      - key: SHOPIFY_CLIENT_SECRET
        sync: false
      - key: SHOPIFY_ACCESS_TOKEN
        sync: false
      - key: SMTP_HOST
        value: smtp-mail.outlook.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: balancereservations@outlook.com
      - key: SMTP_PASS
        sync: false
      - key: FROM_EMAIL
        value: balancereservations@outlook.com
      - key: ADMIN_PASSWORD
        sync: false
      - key: BASE_URL
        value: https://booking-system-nceq.onrender.com
